[phases.setup]
nixPkgs = ["python311", "ffmpeg"]

[phases.install]
cmds = [
  "python -m pip install --upgrade pip",  # Ensure pip is upgraded
  "python -m pip install --no-cache-dir -r requirements.txt"  # Install dependencies
]

[phases.start]
cmds = ["python -m uvicorn app:app --host 0.0.0.0 --port 8080"]