[phases.setup]
nixPkgs = ["python311", "ffmpeg"]

[phases.install]
cmds = [
  "python -m ensurepip --upgrade",  # Ensure pip is installed or upgraded
  "python -m pip install --no-cache-dir -r requirements.txt"  # Install dependencies using python -m pip
]

[phases.start]
cmds = ["python -m uvicorn app:app --host 0.0.0.0 --port 8080"]
