[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "ffmpeg-full"]

[phases.install]
cmds = [
    "python -m pip install --upgrade pip",
    "python -m pip install --no-cache-dir -r requirements.txt"
]

[phases.start]
cmds = ["/root/.nix-profile/bin/python -m uvicorn app:app --host 0.0.0.0 --port 8080"]
