[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "ffmpeg"]

[phases.install]
cmds = ["./setup_env.sh"]

[phases.start]
cmds = ["/root/.nix-profile/bin/python -m uvicorn app:app --host 0.0.0.0 --port 8080"]
